### ISSUE TITLE
When only one hit exists OR only one hit passes -S filter, metabin is not assigning at species level

### ISSUE THREAD

**Issue by bastianegeter** [envmetagen/metabinkit#6] opened 2020-05-26 16:29 UTC
(the good news: metabin is installing and runnning well, and is much faster than bin.blast3!)

Example of issue:

Input: tests/test_files/2020_01.blast.filt.txt
metabin output: tests/test_files/2020_01.metabins.txt.tsv
bin.blast3 output: tests/test_files/2020_01.bins3.txt

This OTU (AllMergedReads.Uniq.1004;size=8) has only one hit in the blast.filt.txt file. 

taxids | qseqid | evalue | staxid | pident | qcovs | min_pident | old_taxids | K | P | C | O | F | G | S |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1701145 | AllMergedReads.Uniq.1004;size=8 | 1.24E-45 | 1701145 | 99.057 | 100 | 98.06643 | 1701145 | Eukaryota | Chordata | Mammalia | Lagomorpha | Leporidae | Lepus | Lepus tibetanus

bin.blast3 bins it as 

`Eukaryota;Chordata;Mammalia;Lagomorpha;Leporidae;Lepus;Lepus tibetanus  `

metabin bins it as 

`Eukaryota;Chordata;Mammalia;Lagomorpha;Leporidae;Lepus;NA  
`

bin.blast3 command (top=default of 1 for all levels)

```
bin.blast3(filtered_blastfile = "2020_01.blast.filt.txt",
           ncbiTaxDir = "/home/tutorial/TOOLS/DBS/ncbi_taxonomy/taxdump/May2020/",
           out = "2020_01.bins3.txt",spident = 98,gpident = 95,fpident = 92,abspident = 80)
```
metabin command:
`metabin -i 2020_01.blast.filt.txt -o 2020_01.metabins.txt -S 98 -G 95 -F 92 -A 80 --discard_sp TRUE`

I started going through a few more differences, but so far all have the same likely reason. Note this also occurs when there are originally multiple hits, but only one hit survives -S filter:

qseqids that have   different bin outcomes | possible reason | METABIN | BIN.BLAST3
-- | -- | -- | --
AllMergedReads.Uniq.1004;size=8 | one hit only | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusNA | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusLepus tibetanus
AllMergedReads.Uniq.1009;size=8 | one hit only | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusNA | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusLepus tibetanus
AllMergedReads.Uniq.1015;size=8 | only one hit remaining after S filter | EukaryotaChordataMammaliaArtiodactylaBovidaeGazellaNA | EukaryotaChordataMammaliaArtiodactylaBovidaeGazellaGazella bennettii
AllMergedReads.Uniq.1032;size=8 | one hit only | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusNA | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusLepus tibetanus
AllMergedReads.Uniq.1034;size=8 | only one hit remaining after S filter | EukaryotaChordataMammaliaArtiodactylaCamelidaeCamelusNA | EukaryotaChordataMammaliaArtiodactylaCamelidaeCamelusCamelus dromedarius
AllMergedReads.Uniq.1041;size=7 | only one hit remaining after S filter | EukaryotaChordataMammaliaCarnivoraFelidaeNANA | EukaryotaChordataMammaliaCarnivoraFelidaePantheraPanthera tigris
AllMergedReads.Uniq.1046;size=7 | one hit only | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusNA | EukaryotaChordataMammaliaLagomorphaLeporidaeLepusLepus tibetanus

Metabin info
```
metabinkit v0.0.1
[info] Starting Binning
[info] binning at species level
[info] excluding 32253 entries with pident below 98
[info] Not considering species with 'sp.', numbers or more than one space
[info] applying species top threshold of 1
[info] binned 0 sequences at species level
[info] binning at genus level
[info] excluding 8720 entries with pident below 95
[info] applying genus top threshold of 1
[info] binned 1529 sequences at genus level
[info] binning at family level
[info] excluding 1138 entries with pident below 92
[info] applying family top threshold of 1
[info] binned 826 sequences at family level
[info] binning at higher-than-family level
[info] excluding 36 entries with pident below 80
[info] applying htf top threshold of 1
[info] binned 473 sequences at higher than family level
[info] Total number of binned 2828 sequences
[info] not binned 0 sequences
[info] Complete. 134002 hits from 2828 queries processed in 1.54 mins.
[info] Note: If none of the hits for a BLAST query pass the binning thesholds, the results will be NA for all levels.
                 If the LCA for a query is above kingdom, e.g. cellular organisms or root, the results will be 'unknown' for all levels.
                 Queries that had no BLAST hits, or did not pass the filter.blast step will not appear in results.  
[info] binned table written to 2020_01.metabins.txt.tsv
$total_hits
[1] 134002

$total_queries
[1] 2828

$binned.species.level
[1] 0

$binned.genus.level
[1] 1529

$binned.family.level
[1] 826

$binned.htf.level
[1] 473

$not.binned
[1] 0

[info] Binning complete in 1.57 min
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=pt_PT.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pt_PT.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pt_PT.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_PT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_PT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.8 optparse_1.6.6   

loaded via a namespace (and not attached):
[1] compiler_3.6.0 magrittr_1.5   tools_3.6.0    getopt_1.20.3  stringi_1.4.6 
[6] stringr_1.4.0 
```

**Comment by nunofonseca** [comment] 2020-05-26 23:12
Hi! Should be fixed now (the cause of the problem was the --discard_sp filter). Please reopen the issue if the problem persists. Cheers.

**Closed by nunofonseca** 2020-05-26 23:12 UTC
Labels: bug
